### ISSUE TITLE
Latest ytdl version

### ISSUE THREAD

**Issue by vlatkodrljin** [JamesKyburz/youtube-audio-stream#104]
Module doesn't work with latest ytdl module version (0.14.4)

**Comment by JamesKyburz** [comment]
@vlatkodrljin What error are you getting?

**Comment by vlatkodrljin** [comment]
`internal/process/next_tick.js:142
      throw new TypeError('callback is not a function');
      ^

TypeError: callback is not a function
    at process.nextTick (internal/process/next_tick.js:142:13)
    at endWritable (_stream_writable.js:527:15)
    at PassThrough.Writable.end (_stream_writable.js:489:5)
    at emitThree (events.js:121:20)
    at FfmpegCommand.emit (events.js:194:7)
    at emitEnd (D:\localhost\youtubebits\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at endCB (D:\localhost\youtubebits\node_modules\fluent-ffmpeg\lib\processor.js:544:13)
    at handleExit (D:\localhost\youtubebits\node_modules\fluent-ffmpeg\lib\processor.js:170:11)
    at ChildProcess.<anonymous> (D:\localhost\youtubebits\node_modules\fluent-ffmpeg\lib\processor.js:182:11)
    at emitTwo (events.js:106:13)
`

**Comment by JamesKyburz** [comment]
I noticed not all videos worked with the latest `ytdl-core`

Could you try now with `youtube-audio-stream@0.0.50` ?

**Comment by MFNich** [comment]
Hey, I'm getting a similar error when using youtube-audio-stream with ydtl-core.
Does anyone know why that is? I tried switching versions but it still throws that error.

` throw er; // Unhandled 'error' event
      ^

TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:238:10)
    at PassThrough.Writable.write (_stream_writable.js:272:21)
    at PassThrough.Writable.end (_stream_writable.js:536:10)
    at emitThree (events.js:140:20)
    at DestroyableTransform.emit (events.js:216:7)
    at emitThree (events.js:135:13)
    at FfmpegCommand.emit (events.js:216:7)
    at emitEnd (C:\Users\Matt\code\project-discord\node_modules\fluent-ffmpeg\li
b\processor.js:424:16)
    at C:\Users\Matt\code\project-discord\node_modules\fluent-ffmpeg\lib\process
or.js:433:16
    at C:\Users\Matt\code\project-discord\node_modules\async\dist\async.js:421:1
6
`

**Comment by JamesKyburz** [comment]
Just updated. If it still an issue can you add a comment with the video url?

**Comment by josephrocca** [comment]
If I run this:
 
   require('youtube-audio-stream')('http://youtube.com/watch?v=dQw4w9WgXcQ');

I get this:

```
events.js:165
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer
    at validChunk (_stream_writable.js:257:10)
    at PassThrough.Writable.write (_stream_writable.js:292:21)
    at PassThrough.Writable.end (_stream_writable.js:576:10)
    at DestroyableTransform.emit (events.js:185:15)
    at FfmpegCommand.emit (events.js:180:13)
    at emitEnd (/home/...../node_modules/fluent-ffmpeg/lib/processor.js:424:16)
    at /home/...../node_modules/fluent-ffmpeg/lib/processor.js:433:16
    at /home/...../node_modules/async/dist/async.js:473:16
    at next (/home/...../node_modules/async/dist/async.js:5329:29)
    at /home/...../node_modules/async/dist/async.js:969:16
Emitted 'error' event at:
    at validChunk (_stream_writable.js:261:12)
    at PassThrough.Writable.write (_stream_writable.js:292:21)
    [... lines matching original stack trace ...]
    at /home/...../node_modules/async/dist/async.js:969:16
```

I also tried several other videos and I get the same result. Haven't dug into any of those errors yet - thought I'd just let you know that this still seems to be a problem.

**Comment by Vaerys42** [comment]
Got the same issue
